FROM mongo:6.0 

RUN apt-get update \
    && apt-get install -y mongodb-org-tools mongodb-org-shell \
    && rm -rf /var/lib/apt/lists/*


COPY config/mongod.conf /etc/mongod.conf


CMD ["mongod", "--config", "/etc/mongod.conf"]


